name: ibrahima_s_application_seter
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  permission_handler: ^11.0.1
  flutter_localizations: 
    sdk: flutter
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  video_player: ^2.2.13
  chewie: ^1.2.2
  flutter_local_notifications: ^9.1.6
  timezone: ^0.8.0
  webview_flutter: ^3.0.0
  flutter_map: ^5.0.0
  cupertino_icons: ^1.0.0
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0
  flutter_svg_provider: ^1.0.7
  sms_autofill: ^2.3.0
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  location: ^6.0.1
  intl: ^0.18.0
  firebase_core: ^2.25.5
  firebase_auth: ^4.0.0
  firebase_database: ^10.4.9
  telephony: ^0.2.0
  lottie: ^3.1.0
  http: ^1.1.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.1.0
  translator: ^1.0.0
  csv: ^6.0.0
  googleapis_auth: ^1.6.0
  flutter_langdetect: ^0.0.2
  googleapis: ^13.1.0
  flutter_osm_plugin: ^0.70.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
flutter_icons:
    image_path: "assets/images/Ter_launcher.png"
    android: true
    iso: true
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/TerNumbLogin.jpg
  fonts: 
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansItalicBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Abyssinica SIL
      fonts: 
        - asset: assets/fonts/AbyssinicaSILRegular.ttf
          weight: 400
    - family: Cutive
      fonts: 
        - asset: assets/fonts/CutiveRegular.ttf
          weight: 400
    - family: Actor
      fonts: 
        - asset: assets/fonts/ActorRegular.ttf
          weight: 400
    - family: Gabriela
      fonts: 
        - asset: assets/fonts/GabrielaRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterLight.ttf
          weight: 300
    - family: Adobe Blank
      fonts: 
        - asset: assets/fonts/AdobeBlankRegular.ttf
          weight: 400
